---
title: "Hackathon"
author: "Group2"
date: "2025-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(flextable)
```

## загрузка данных

```{r cars}
data_team_02 <- read_csv("Data/team_2.csv")



data_team_02 <-data_team_02%>% 
  mutate(
    V0_DEM_GEN = as.factor(V0_DEM_GEN),
    V0_GRP = as.factor(V0_GRP)
  )
 
```

## создание функции для расчета статистик

```{r}
statistics_dbl <- list(
  
  # Количество значений
  `__Количество значений` = ~ length(.x) %>% as.character(),

  # Среднее значение (если нет значений, возвращает "Н/П*")
  `__Ср. знач.` = ~ ifelse(
    sum(!is.na(.x)) == 0,
    "Н/П*",
    mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()
  ),

  # 95% ДИ (если нет значений, возвращает "Н/П*")
  `__95% ДИ` = ~ ifelse(
    sum(!is.na(.x)) == 0,
    "Н/П*",
    paste0(
      t.test(.x)$conf.int[1] %>% round(2),
      "   ",
      t.test(.x)$conf.int[2] %>% round(2)
    ) %>% as.character()
  ),

  # Коэффициент вариации 
  `__Коэф. вариации` = ~ ifelse(
    sum(!is.na(.x)) < 2,  # Изменено условие для обработки недостаточных значений
    "Н/П*",
    (sd(.x, na.rm = TRUE) / mean(.x, na.rm = TRUE)) %>% round(2) %>% as.character()
  ),

  # Стандартное отклонение (если менее 3 значений, возвращает "Н/П*")
  `__Станд. отклон.` = ~ ifelse(
    sum(!is.na(.x)) < 3,
    "Н/П*",
    sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()
  ),

  # Медиана (если нет значений, возвращает "Н/П*")
  `__Медиана` = ~ ifelse(
    sum(!is.na(.x)) == 0,
    "Н/П*",
    median(.x, na.rm = TRUE) %>% round(2) %>% as.character()
  ),

  # Межквартильный размах (если нет значений, возвращает "Н/П*")
  `__IQR` = ~ ifelse( 
    sum(!is.na(.x)) == 0,
    "Н/П*",
    IQR(.x, na.rm = TRUE) %>% round(2) %>% as.character()
  ),

  # Минимум (если нет значений, возвращает "Н/П*")
  `__минимум` = ~ ifelse(
    sum(!is.na(.x)) == 0,
    "Н/П*",
    min(.x, na.rm = TRUE) %>% round(2) %>% as.character()
  ),

  # Максимум (если нет значений, возвращает "Н/П*")
  `__максимум` = ~ ifelse(
    sum(!is.na(.x)) == 0,
    "Н/П*",
    max(.x, na.rm = TRUE) %>% round(2) %>% as.character()
  )
)
```


## Расчет описательных статистик и формирование таблицы

```{r}
#  Теперь выберем переменные которые будем считать 
 data_team_02 %>%
  select(V0_DEM_GEN, V0_GRP, where(is.numeric)) %>%
   # сгруппируем по  V0_GRP
  group_by(V0_GRP) %>% 
   # добавим статистик
  summarize(across(where(is.numeric), statistics_dbl )) %>% 
   # сделаем таблицу в длинном формате 
  pivot_longer(!V0_GRP) %>% 
  separate(name, into=c("Переменная", "Статистика"), sep= "___") ->a1
 
 a1 %>%
  flextable() %>% 
  theme_box() %>% 
  align(align = "center", part = "all") %>% 
  merge_v(c("V0_GRP", "Переменная"))  


```



## НЕЖЕЛАТЕЛЬНЫЕ ЯВЛЕНИЯ

```{r}
a2 <- data_team_02 %>%
  mutate(adverse_RMDQ  = ifelse((V1_RMDQ < V2_RMDQ)  |
                                  (V1_RMDQ < V3_RMDQ) | (V2_RMDQ < V3_RMDQ) ,
                                1, 0),
         adverse_ECG = ifelse(
           (V1_NORM_ECG < V2_NORM_ECG)  |
             (V1_NORM_ECG < V3_NORM_ECG) | (V2_NORM_ECG < V3_NORM_ECG),
           1, 0),

          adverse_PHYS = ifelse(
        (V1_NORM_PHYS < V2_NORM_PHYS)  |
             (V1_NORM_PHYS < V3_NORM_PHYS) | (V2_NORM_PHYS< V3_NORM_PHYS),
           1, 0),

          adverse_VIT = ifelse(
        (V1_NORM_VIT < V2_NORM_VIT)  |
             (V1_NORM_VIT < V3_NORM_VIT) | (V2_NORM_VIT< V3_NORM_VIT),
           1, 0),

  )




# Функция для определения нежелательных явлений
detect_adverse_events <- function(data) {
  data_team_02 %>%
    # Проверка изменений для ЭКГ, физических обследований и витальных функций
    mutate(
      # ЭКГ
      ECG_adverse = ifelse(
        (V1_NORM_ECG == 0 & (V2_NORM_ECG == 1 | V3_NORM_ECG == 1)) |
        (V2_NORM_ECG == 0 & V3_NORM_ECG == 1),
        1, 0
      ),
      # Физические обследования
      PHYS_adverse = ifelse(
        (V1_NORM_PHYS == 0 & (V2_NORM_PHYS == 1 | V3_NORM_PHYS == 1)) |
        (V2_NORM_PHYS == 0 & V3_NORM_PHYS == 1),
        1, 0
      ),
      # Витальные функции
      VIT_adverse = ifelse(
        (V1_NORM_VIT == 0 & (V2_NORM_VIT == 1 | V3_NORM_VIT == 1)) |
        (V2_NORM_VIT == 0 & V3_NORM_VIT == 1),
        1, 0
      )
    ) %>%
    # Проверка изменений для показателей крови
    #mutate(
      #across(
        #starts_with("V1_CB_") & !ends_with("_NORM"),
        #~ ifelse(
          #(V1_NORM_ECG == 0 & (V2_NORM_ECG == 1 | V2_NORM_ECG == 2 | V3_NORM_ECG == 1 | V3_NORM_ECG == 2)) |
          #(V2_NORM_ECG == 0 & (V3_NORM_ECG == 1 | V3_NORM_ECG == 2)), 1, 0),.names = "CB_adverse_{col}")) %>%
    
    # Определение нежелательных явлений для RMDQ
    mutate(
      adverse_RMDQ = ifelse(
        (V1_RMDQ < V2_RMDQ | V1_RMDQ < V3_RMDQ) | V2_RMDQ < V3_RMDQ,
        1, 0)
    ) %>%
    # Общий флаг нежелательных явлений
    mutate(
      adverse_event = ifelse(
        ECG_adverse == 1 | PHYS_adverse == 1 | VIT_adverse == 1 | 
       # rowSums(across(starts_with("CB_adverse_"))) > 0 | 
          adverse_RMDQ == 1,
        1, 0
      )
    )
}

# Применение функции к данным
data_with_adverse_events <- detect_adverse_events(data_team_02)

# Фильтрация пациентов с нежелательными явлениями
adverse_events_T <- data_with_adverse_events %>%
  filter(V0_GRP == "T" & adverse_event == 1)

adverse_events_R <- data_with_adverse_events %>%
  filter(V0_GRP == "R" & adverse_event == 1)

# Вывод результатов
cat("Пациенты с нежелательными явлениями в группе T (препарат):\n")
print(adverse_events_T)

cat("\nПациенты с нежелательными явлениями в группе R (референс):\n")
print(adverse_events_R)
```







